### PR TITLE
Many GPTQ updates adapted for Kobold

### PR DESCRIPTION
**Pull request by 0cc4m**

### CODE REVIEW

**Comment by Ph0rk0z** [comment]
Is this going to use the V2 format or just the old format with safetensors support?

**Comment by 0cc4m** [comment]
@Ph0rk0z It adapts many of the changes in upstream GPTQ, including support for groupsize parameter and the new quantization format. I assume this is what you refer to as V2?

**Comment by Ph0rk0z** [comment]
Yes, the new format.. although there is a 3rd format now? 

Also for neox were you able to quantize GPT-NeoXT-Chat-Base-20B?

For some reason this fails to either generate or as I found this morning convert.

This is what it did: https://pastebin.com/8TqrYP7q

**Comment by 0cc4m** [comment]
@Ph0rk0z I had the same issue with large gpt-neox models, specifically 20B and Pythia-12B. I don't know what causes that or how you would fix it, sadly.

**Comment by Ph0rk0z** [comment]
@0cc4m 

Someone somehow converted these but the chatbase doesn't work. The pythia does.

OSST (oldGPTQ)
https://drive.google.com/file/d/1lAlID8RwFKOEvQSHt6owcg9hGvBSc5EY/view?usp=share_link

NeoXT-Chatbot-Base (oldGPTQ)
https://drive.google.com/file/d/1OaKKqUFVffExi5fGezwYrMjG6Ac3romV/view?usp=share_link

Maybe the new GPTQ it will convert it.

**Comment by Ph0rk0z** [comment]
@0cc4m 

Well I can convert pythia and lotus 12b with the new converter.

https://huggingface.co/autobots/lotus-12b-gptqv2-4bit

**Comment by 0cc4m** [comment]
@Ph0rk0z Which is the new converter? Just upstream qwopwop/GPTQ?

**Comment by Ph0rk0z** [comment]
@occ4am I used the one you made here. The previous neox branch is v1 only.

btw pythia finished too: https://huggingface.co/autobots/pythia-12b-gptqv2-4bit

I wish the benchmarks would run though.

**Pull request closed without merging**
